### ISSUE TITLE
TinyPNG

### ISSUE THREAD

**Issue by lifeinchords** [jwa107/Photoshop-Export-Layers-as-Images#33]
Hi there
I've just picked up TinyPNG which is a fantastic plugin for seriously reducing file sizes of PNG-24 with transparency. Went from a 250kb file down to 65kb. 

What modifications do I need to make to this script to export using [TinyPNG](https://tinypng.com/photoshop)?

[This](http://voormedia.com/blog/2014/06/compressing-png-images-in-photoshop-with-javascript-and-tinypng) might be relevant.. 

Much appreciated
=: s

**Comment by jwa107** [comment]
I don't see our script ever including TinyPNG as it is a separate (and paid) plug-in. However in the second link you've referenced there's a section about compressing all files and subfolders. So I would recommend you run our script, and then [run that one](https://gist.github.com/rolftimmermans/936eb3abf99776070830) afterwards to get what you want.

As far as how to set-up and write a script I'm afraid this isn't the place for it.  Adobe has [documentation](http://www.adobe.com/devnet/photoshop/scripting.html) on scripting.

**Comment by lifeinchords** [comment]
Hi,

That's exactly what I've done, and it's worked.

Thanks for the quick and detailed response

=: s

**Comment by skjorn** [comment]
If you want to save some time on recompressing PNGs, you can do the following:

1. Find the function 'exportPng24AM' in our script.
2. Replace the content with:
```
  var tinypng = new ActionDescriptor();
  tinypng.putPath(charIDToTypeID("In  "), fileName);

  var compress = new ActionDescriptor();
  compress.putObject(charIDToTypeID("Usng"), charIDToTypeID("tinY"), tinypng);
  executeAction(charIDToTypeID("Expr"), compress, DialogModes.NO);
```
This will use TinyPNG for every PNG-24 export. (Format specific parameters will be ignored.)
If you're savvy enough, you can even copy the function and change that instead. Then integrate it with the rest of the code by searching where and how the original function is called. This way you could have a separate TinyPNG option.

**Comment by lifeinchords** [comment]
Thank you! super helpful!



      ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈

         Steven J. Dale   @lifeinchords <https://twitter.com/lifeinchords>
 @makeparallels <http://www.twitter.com/makeparallels>

      ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
